
telegram:
  token: 12345:abcdefg
  group_id: -123456789
  
twitter:
  api_key: xxx
  api_secret: yyy
  access_token: aaa 
  access_token_secret: bbb

wallet:
  donations: "0xDbC82..abDC7"

nodes:
  ethereum: https://node.com 
  zksync: https://zksync.api

database:
  filename: orgabot.db